{{- if .Values.resilience.horizontalPodAutoscaler.enabled }}
# HorizontalPodAutoscalers automatically scale pods based on CPU/memory usage
# This is a Kubernetes native feature for handling traffic spikes
#
# Works together with Istio's circuit breaker:
# - HPA scales up when load increases
# - Circuit breaker protects when services fail
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.resilience.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.resilience.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.resilience.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
  {{- if .Values.resilience.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.resilience.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
  {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productcatalogservice-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogservice
  minReplicas: {{ .Values.resilience.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.resilience.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.resilience.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: checkoutservice-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkoutservice
  minReplicas: {{ .Values.resilience.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.resilience.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.resilience.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
{{- end }}
