{{- if .Values.istio.enabled }}
{{- if .Values.istio.retry.enabled }}
# VirtualServices for Retry and Timeout configuration
# These implement automatic retries with exponential backoff for transient failures
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productcatalogservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - productcatalogservice
  http:
  - route:
    - destination:
        host: productcatalogservice
    retries:
      attempts: {{ .Values.istio.retry.attempts }}
      perTryTimeout: {{ .Values.istio.retry.perTryTimeout }}
      retryOn: {{ .Values.istio.retry.retryOn }}
    timeout: {{ .Values.istio.retry.timeout }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: currencyservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - currencyservice
  http:
  - route:
    - destination:
        host: currencyservice
    retries:
      attempts: {{ .Values.istio.retry.attempts }}
      perTryTimeout: {{ .Values.istio.retry.perTryTimeout }}
      retryOn: {{ .Values.istio.retry.retryOn }}
    timeout: {{ .Values.istio.retry.timeout }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cartservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - cartservice
  http:
  - route:
    - destination:
        host: cartservice
    retries:
      attempts: {{ .Values.istio.retry.attempts }}
      perTryTimeout: {{ .Values.istio.retry.perTryTimeout }}
      retryOn: {{ .Values.istio.retry.retryOn }}
    timeout: {{ .Values.istio.retry.timeout }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recommendationservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - recommendationservice
  http:
  - route:
    - destination:
        host: recommendationservice
    retries:
      attempts: {{ .Values.istio.retry.attempts }}
      perTryTimeout: {{ .Values.istio.retry.perTryTimeout }}
      retryOn: {{ .Values.istio.retry.retryOn }}
    timeout: {{ .Values.istio.retry.timeout }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: checkoutservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - checkoutservice
  http:
  - route:
    - destination:
        host: checkoutservice
    retries:
      attempts: {{ .Values.istio.retry.attempts }}
      perTryTimeout: {{ .Values.istio.retry.perTryTimeout }}
      retryOn: {{ .Values.istio.retry.retryOn }}
    timeout: {{ .Values.istio.retry.timeout }}
{{- end }}
{{- end }}
